version: "3"
services:
  redis:
    ports:
      - "6379:6379"
    build: ./docker_redis        
    restart: always
    network_mode: host
  db:
    image: "mongo"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
        - "27017:27017"
    network_mode: host
    command: mongod --quiet --logpath /dev/null 
  web:
    build: .
    ports:
      - "8000:8000"
    network_mode: host
  
