version: "3"
services:
  redis:
    ports:
      - "6379:6379"
    build: ./docker_images/redis
    restart: always
  balancer:
    build:
      dockerfile: "./docker_images/balancer/Dockerfile"
      context: "./"
    ports:
      - "8000:8000"
    restart: always
  backend:
    build: ./docker_images/backend
    ports:
      - "8080-8082:8000"
    restart: always
